version: "3.5"
services:
  centos7imagick:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
  centos7imagickrel:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.rel
  centos8imagick:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm8:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.el8
  centos8imagickrel:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm8:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.8-rel

volumes:
  rpms:
    name: rpms
  rpm7:
    name: rpm7
  rpm8:
    name: rpm8
