version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    environment:
      IMAGICK_VERSION: 6.9.9.38-2
      PACKAGE_VCS_URL: https://github.com/aursu/rpmbuild-php-imagick
    steps:
      - run:
          name: Upgrade Docker CE
          command: |
            sudo apt-get update
            sudo apt-get install docker-ce=18.03.1~ce-0~ubuntu
      - run:
          name: Upgrade Docker Compose
          command: |
            sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Create Build User/Group
          command: |
            if getent group centos; then
              sudo groupmod -o -g 48 centos
            else
              sudo groupadd -o -g 48 centos
            fi

            if getent passwd centos; then
              sudo usermod -o -u 48 -g centos centos
            else
              sudo useradd -o -u 48 -g centos -M -d /var/www/html centos
            fi
      - checkout
      - run:
          name: Git submodules sync
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Start docker services for rpmbuild
          command: |
            docker-compose -f rpmbuild/docker-compose.yml pull
            docker-compose -f rpmbuild/docker-compose.yml up -d
          background: true
          no_output_timeout: 2h
      - restore_cache:
          keys:
            - rpm-cache-v7-{{ checksum "requirements.txt" }}-{{ checksum "SPECS/php-pecl-imagick.spec" }}
            - rpm-cache-v7-{{ checksum "requirements.txt" }}-
            - rpm-cache-v7-
      - run:
          name: Restore Repository
          command: |
            sleep 30
            if [ -d ~/el6/RPMS ]; then
              sudo chown -R centos:centos ~/el6/RPMS
              docker cp -a ~/el6/RPMS rpmbuild_webrepo_1:/home/centos-6/rpmbuild/
            fi
            if [ -d ~/el7/RPMS ]; then
              sudo chown -R centos:centos ~/el7/RPMS
              docker cp -a ~/el7/RPMS rpmbuild_webrepo_1:/home/centos-7/rpmbuild/
            fi
      - run:
          name: Checkout ImageMagick
          command: |
            git clone https://github.com/aursu/rpmbuild-imagick.git
            cd rpmbuild-imagick
            git checkout $IMAGICK_VERSION
      - run:
          name: Build ImageMagick
          command: |
            docker run -ti --rm --net buildnet -u root aursu/rpmbuild:7-build \
            yum -q list --disablerepo=* --enablerepo custom ImageMagick-devel | grep -q $IMAGICK_VERSION ||
            {
              docker pull aursu/imagickbuild:el7
              docker-compose -f rpmbuild-imagick/docker-compose.yml up centos7imagickbuild
            }
            docker run -ti --rm --net buildnet -u root aursu/rpmbuild:6-build \
            yum -q list --disablerepo=* --enablerepo custom ImageMagick-devel | grep -q $IMAGICK_VERSION ||
            {
              docker pull aursu/imagickbuild:el6
              docker-compose -f rpmbuild-imagick/docker-compose.yml up centos6imagickbuild
            }
      - run:
          name: Build Docker images
          command: |
            sleep 30
            docker-compose build --no-cache
      - run:
          name: Build RPM packages
          command: docker-compose up
      - run:
          name: Copy RPM packages
          command: |
            sudo rm -rf ~/el6 ~/el7
            mkdir -p ~/el6 ~/el7
            docker cp rpmbuild_webrepo_1:/home/centos-6/rpmbuild/RPMS ~/el6/
            docker cp rpmbuild_webrepo_1:/home/centos-7/rpmbuild/RPMS ~/el7/
            sudo chown -R centos:centos ~/el6/RPMS ~/el7/RPMS
      - save_cache:
          key: rpm-cache-v7-{{ checksum "requirements.txt" }}-{{ checksum "SPECS/php-pecl-imagick.spec" }}
          paths:
            - ~/el6/RPMS
            - ~/el7/RPMS
      - run:
          name: Upload RPM packages into Bintray
          command: |
            docker-compose -f rpmbuild/docker-compose.bintray.yml pull
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=$BINTRAY_REPO \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos7bintray
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=$BINTRAY_REPO \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos6bintray
      - run:
          name: Upload Docker images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            sleep 30
            docker push aursu/peclbuild:7-imagick-base
            docker push aursu/peclbuild:6-imagick-base
            docker push aursu/peclbuild:7-imagick
            docker push aursu/peclbuild:6-imagick
      - store_artifacts:
          path: ~/el6/RPMS
      - store_artifacts:
          path: ~/el7/RPMS
  build5:
    machine:
      docker_layer_caching: true
    environment:
      IMAGICK_VERSION: 6.9.9.38-2
      BINTRAY_REPO: php5custom
      PACKAGE_VCS_URL: https://github.com/aursu/rpmbuild-php-imagick
    steps:
      - run:
          name: Upgrade Docker CE
          command: |
            sudo apt-get update
            sudo apt-get install docker-ce=18.03.1~ce-0~ubuntu
      - run:
          name: Upgrade Docker Compose
          command: |
            sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Create Build User/Group
          command: |
            if getent group centos; then
              sudo groupmod -o -g 48 centos
            else
              sudo groupadd -o -g 48 centos
            fi

            if getent passwd centos; then
              sudo usermod -o -u 48 -g centos centos
            else
              sudo useradd -o -u 48 -g centos -M -d /var/www/html centos
            fi
      - checkout
      - run:
          name: Git submodules sync
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Start docker services for rpmbuild
          command: |
            docker-compose -f rpmbuild/docker-compose.yml pull
            docker-compose -f rpmbuild/docker-compose.yml up -d
          background: true
          no_output_timeout: 2h
      - restore_cache:
          keys:
            - rpm-cache-v5-{{ checksum "requirements.txt" }}-{{ checksum "SPECS/php-pecl-imagick.spec" }}
            - rpm-cache-v5-{{ checksum "requirements.txt" }}-
            - rpm-cache-v5-
      - run:
          name: Restore Repository
          command: |
            sleep 30
            if [ -d ~/php5/el6/RPMS ]; then
              sudo chown -R centos:centos ~/php5/el6/RPMS
              docker cp -a ~/php5/el6/RPMS rpmbuild_webrepo_1:/home/centos-6/rpmbuild/
            fi
            if [ -d ~/php5/el7/RPMS ]; then
              sudo chown -R centos:centos ~/php5/el7/RPMS
              docker cp -a ~/php5/el7/RPMS rpmbuild_webrepo_1:/home/centos-7/rpmbuild/
            fi
      - run:
          name: Checkout ImageMagick
          command: |
            git clone https://github.com/aursu/rpmbuild-imagick.git
            cd rpmbuild-imagick
            git checkout $IMAGICK_VERSION
      - run:
          name: Build ImageMagick
          command: |
            docker run -ti --rm --net buildnet -u root aursu/rpmbuild:7-build \
            yum -q list --disablerepo=* --enablerepo custom ImageMagick-devel | grep -q $IMAGICK_VERSION ||
            {
              docker pull aursu/imagickbuild:el7
              docker-compose -f rpmbuild-imagick/docker-compose.yml up centos7imagickbuild
            }
            docker run -ti --rm --net buildnet -u root aursu/rpmbuild:6-build \
            yum -q list --disablerepo=* --enablerepo custom ImageMagick-devel | grep -q $IMAGICK_VERSION ||
            {
              docker pull aursu/imagickbuild:el6
              docker-compose -f rpmbuild-imagick/docker-compose.yml up centos6imagickbuild
            }
      - run:
          name: Build Docker images (PHP 5)
          command: |
            sleep 30
            docker-compose -f docker-compose.php5.yml build --no-cache
      - run:
          name: Build RPM packages (PHP 5)
          command: docker-compose -f docker-compose.php5.yml up
      - run:
          name: Upload RPM packages into Bintray
          command: |
            docker-compose -f rpmbuild/docker-compose.bintray.yml pull
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=$BINTRAY_REPO \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos7bintray
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=$BINTRAY_REPO \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos6bintray
      - run:
          name: Copy RPM packages (PHP 5)
          command: |
            sudo rm -rf ~/php5
            mkdir -p ~/php5/el6 ~/php5/el7
            docker cp rpmbuild_webrepo_1:/home/centos-6/rpmbuild/RPMS ~/php5/el6/
            docker cp rpmbuild_webrepo_1:/home/centos-7/rpmbuild/RPMS ~/php5/el7/
            sudo chown -R centos:centos ~/php5/*
      - run:
          name: Upload Docker images (PHP 5)
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            sleep 30
            docker push aursu/peclbuild:7-imagick-base-php5
            docker push aursu/peclbuild:6-imagick-base-php5
            docker push aursu/peclbuild:7-imagick-php5
            docker push aursu/peclbuild:6-imagick-php5
      - save_cache:
          key: rpm-cache-v5-{{ checksum "requirements.txt" }}-{{ checksum "SPECS/php-pecl-imagick.spec" }}
          paths:
            - ~/php5
      - store_artifacts:
          path: ~/php5
workflows:
  version: 2
  imagickbuild:
    jobs:
      - build
      - build5
