version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.7

parameters:
  artifactory-url:
    description: Artifactory URL
    type: string
    default: https://rpmb.jfrog.io

workflows:
  igbinarybuild:
    jobs:
      - docker-rpmbuild/build:
          name: centos7imagick
          build_service: centos7imagick
          bintray-repo: php74custom
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8imagick
          build_service: centos8imagick
          bintray-repo: php74custom
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7imagickphp73
          build_file: docker-compose.php73.yml
          build_service: centos7imagickphp73
          bintray-repo: php73custom
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8imagickphp73
          build_file: docker-compose.php73.yml
          build_service: centos8imagickphp73
          bintray-repo: php73custom
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7imagickphp80
          build_file: docker-compose.php80.yml
          build_service: centos7imagickphp80
          bintray-repo: php8custom
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8imagickphp80
          build_file: docker-compose.php80.yml
          build_service: centos8imagickphp80
          bintray-repo: php8custom
          bintray_uploader: centos8bintray